name: Build Clash Config

on:
  workflow_dispatch:
  push:
    paths:
      - config.template.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Render config
        run: |
          envsubst < config.template.yaml > config.yaml
        env:
          BWG_SERVER: ${{ secrets.BWG_SERVER }}
          KR_SERVER: ${{ secrets.KR_SERVER }}
          OVH_SERVER: ${{ secrets.OVH_SERVER }}
          SNELLSERVER: ${{ secrets.SNELLSERVER }}
          PORT: ${{ secrets.PORT }}
          SNELL_PORT: ${{ secrets.SNELL_PORT }}
          ALLPASS: ${{ secrets.ALLPASS }}

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Clash Config
          files: config.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
