name: Build Clash Config

on:
  push:
    paths:
      - config.template.yaml
  workflow_dispatch:

permissions:
  contents: write   # 非常关键，否则无法 commit

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Render config.yaml from template
        env:
          BWG_SERVER: ${{ secrets.BWG_SERVER }}
          KR_SERVER: ${{ secrets.KR_SERVER }}
          OVH_SERVER: ${{ secrets.OVH_SERVER }}
          SNELL: ${{ secrets.SNELL }}
          PORT: ${{ secrets.PORT }}
          SNELL_PORT: ${{ secrets.SNELL_PORT }}
          ALLPASS: ${{ secrets.ALLPASS }}
        run: |
          envsubst < config.template.yaml > config.yaml

      - name: Commit config.yaml
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add config.yaml
          git commit -m "auto: update config.yaml" || echo "No changes"
          git push
